app:
  datasource:
    jdbc-url: jdbc:postgresql://${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}
    username: admin
    password: ${{ secrets.DB_PASSWORD }}
    pool-size: 30

server:
  port: 8080

