name: Build, push docker images and Deploy

on:
  push:
    branches: [main]

jobs:
  Build-Push-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
          tags: latest
          registry: docker.io
          dockerfile: ./Dockerfile
          directory: ./
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  Deploy-Application:
    runs-on: ubuntu-latest
    needs: Build-Push-Image
    steps:
      - name: SSH On Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_IMAGE}}
            docker rm -f mortgage
            docker run -p 8080:8080 --name mortgage --restart=on-failure -d ${{ secrets.DOCKER_IMAGE }}
